
variables:
  pytorch.build.version: 1.0
  pytorch.build.number: 1
  pytorch.branch: master # override the default of build.version
  pytorch.repo: pytorch
  build.linux.enabled: false
  build.cpu.enabled: true
  build.cuda.enabled: true
  build.wheels.enabled: true
  build.conda.enabled: true
  use.sccache.cpu: 0
  use.sccache.cuda: 1
  self.hosted.agent.cpu: false
  self.hosted.agent.cuda: true

jobs:
- job: 'Windows_CPU_Wheels_Build'
  timeoutInMinutes: 0
  cancelTimeoutInMinutes: 5
  condition: and(eq(variables['build.cpu.enabled'], 'true'), eq(variables['build.wheels.enabled'], 'true'))
  variables:
    PACKAGE: wheels
    CUDA_VERSION: cpu
    USE_SCCACHE: $(use.sccache.cpu)
  strategy:
    maxParallel: 10
    matrix:
      PY3.7:
        DESIRED_PYTHON: 3.7

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: BatchScript@1
    displayName: 'Make fake whl'
    inputs:
      filename: 'windows/internal/tmp_make_fake_whl.bat'
      modifyEnvironment: false

  - template: windows/templates/upload_to_s3.yml
    parameters:
      cuVer: 'cpu'
